### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Emrix** [NERDDISCO/luminave-fivetwelve#8]
I am getting this error:
![Screen Shot 2019-08-02 at 7 15 24 PM](https://user-images.githubusercontent.com/1387836/62405451-7ec47880-b55a-11e9-92e6-150c99f69247.png)

And I am not getting the lights to react to the rest of the system.   I know everything is set up correctly, because I can get the lights to update on a different software.  I'm using Thorium with it.

**Comment by TimPietrusky** [comment]
@Emrix can you please update your local luminave-fivetwelve and see if the problem is gone?
